### ISSUE TITLE
Greetings must be possible in English and Danish

### ISSUE THREAD

**Issue by allanhojgaardjensen** [cppdk/ezy-dev2ops#3]
The greetings must not only be done in Danish as is the current possibility.
It is desirable to have that in English as well.

**Comment by allanhojgaardjensen** [comment]
Requires service to support languages - starting with English
[Service issue created](https://github.com/cppdk/greeting-rest-service/issues/1)

**Comment by allanhojgaardjensen** [comment]
Requires client to signal language
[Client Issues created](https://github.com/cppdk/greeting-rest-service-client/issues/1)

**Comment by AllanHoejgaardJensen** [comment]
Implemented

**Comment by allanhojgaardjensen** [comment]
Implemented
